Models/ErrorViewModel.cs
using System;

namespace NetCoreCharts.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SimpleReportViewModel.cs
namespace NetCoreCharts.Models {
    public class SimpleReportViewModel {
        public string DimensionOne { get; set; }
        public int Quantity { get; set; }
    }
}

Models/StackedViewModel.cs
using System.Collections.Generic;

namespace NetCoreCharts.Models {
    public class StackedViewModel {
        public string StackedDimensionOne { get; set; }
        public List<SimpleReportViewModel> LstData { get; set; }
    }
}

Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using NetCoreCharts.Models;

namespace NetCoreCharts.Controllers {
    public class ChartsController : Controller {
        private Random rnd = new Random ();

        public IActionResult Bar () {
            //list of department
            var lstModel = new List<SimpleReportViewModel> ();
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Technology",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Sales",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Marketing",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Human Resource",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Research and Development",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Acconting",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Support",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Logistics",
                    Quantity = rnd.Next (10)
            });
            return View (lstModel);
        }

        public IActionResult Line () {
            //list of countries
            var lstModel = new List<SimpleReportViewModel> ();
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Brazil",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "USA",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Portugal",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Russia",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Ireland",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Germany",
                    Quantity = rnd.Next (10)
            });
            return View (lstModel);
        }

        public IActionResult Pie () {
            //list of drinks
            var lstModel = new List<SimpleReportViewModel> ();
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Beer",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Wine",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Whisky",
                    Quantity = rnd.Next (10)
            });
            lstModel.Add (new SimpleReportViewModel {
                DimensionOne = "Water",
                    Quantity = rnd.Next (10)
            });
            return View (lstModel);
        }

        public IActionResult Stacked () {
            var lstModel = new List<StackedViewModel> ();
            //sales of product sales by quarter
            lstModel.Add (new StackedViewModel {
                StackedDimensionOne = "First Quarter",
                    LstData = new List<SimpleReportViewModel> () {
                        new SimpleReportViewModel () {
                                DimensionOne = "TV",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Games",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Books",
                                    Quantity = rnd.Next (10)
                            }
                    }
            });
            lstModel.Add (new StackedViewModel {
                StackedDimensionOne = "Second Quarter",
                    LstData = new List<SimpleReportViewModel> () {
                        new SimpleReportViewModel () {
                                DimensionOne = "TV",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Games",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Books",
                                    Quantity = rnd.Next (10)
                            }
                    }
            });
            lstModel.Add (new StackedViewModel {
                StackedDimensionOne = "Third Quarter",
                    LstData = new List<SimpleReportViewModel> () {
                        new SimpleReportViewModel () {
                                DimensionOne = "TV",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Games",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Books",
                                    Quantity = rnd.Next (10)
                            }
                    }
            });
            lstModel.Add (new StackedViewModel {
                StackedDimensionOne = "Fourth Quarter",
                    LstData = new List<SimpleReportViewModel> () {
                        new SimpleReportViewModel () {
                                DimensionOne = "TV",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Games",
                                    Quantity = rnd.Next (10)
                            },
                            new SimpleReportViewModel () {
                                DimensionOne = "Books",
                                    Quantity = rnd.Next (10)
                            }
                    }
            });
            return View (lstModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetCoreCharts.Models;

namespace NetCoreCharts.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Charts/Bar.cshtml
@model List<SimpleReportViewModel>
@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.DimensionOne ).ToList() );
    var YValues = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.Quantity ).ToList() );
    ViewData["Title"] = "Bar Chart";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bar</title>
</head>
<body>
    <div class="box-body">

        <div class="chart-container">
            <canvas id="chart" style="width:100%; height:500px"></canvas>
        </div>
    </div>
</body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
        $(function () {
    var chartName = "chart";
        var ctx = document.getElementById(chartName).getContext('2d');
        var data = {
                labels: @Html.Raw(XLabels),
                datasets: [{
                    label: "Departments Chart",
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderWidth: 1,
                    data: @Html.Raw(YValues)
    }]
            };

var options = {
                maintainAspectRatio: false,
                scales: {
                    yAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: true,
                            color: "rgba(255,99,164,0.2)"
                        }
}],
                    xAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: false
                        }
                    }]
                }
            };

       var myChart = new  Chart(ctx, {
                options: options,
                data: data,
                type:'bar'

            });
        });
</script>

Views/Charts/Line.cshtml
@model List<SimpleReportViewModel>
@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.DimensionOne ).ToList() );
    var YValues = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.Quantity ).ToList() );
    ViewData["Title"] = "Line Chart";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Line</title>
</head>
<body>
    <div class="box-body">

        <div class="chart-container">
            <canvas id="chart" style="width:100%; height:500px"></canvas>
        </div>
    </div>
</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
        $(function () {
    var chartName = "chart";
        var ctx = document.getElementById(chartName).getContext('2d');
        var data = {
                labels: @Html.Raw(XLabels),
                datasets: [{
                    label: "Countries Chart",
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderWidth: 1,
                    //hoverBackgroundColor: "rgba(255,99,132,0.4)",
                    //hoverBorderColor: "rgba(255,99,132,1)",
                    data: @Html.Raw(YValues)
    }]
            };

var options = {
                maintainAspectRatio: false,
                scales: {
                    yAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: true,
                            color: "rgba(255,99,164,0.2)"
                        }
}],
                    xAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: false
                        }
                    }]
                }
            };

       var myChart = new  Chart(ctx, {
                options: options,
                data: data,
                type:'line'

            });
        });
</script>

Views/Charts/Pie.cshtml
@using System.Linq;
@model List<SimpleReportViewModel>
@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.DimensionOne ).ToList() );
    var YValues = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.Quantity ).ToList() );
    ViewData["Title"] = "Pie Chart";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pie</title>
</head>
<body>
    <div class="box-body">

        <div class="chart-container">
            <canvas id="chart" style="width:100%; height:500px"></canvas>
        </div>
    </div>
</body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
        $(function () {
    var chartName = "chart";
        var ctx = document.getElementById(chartName).getContext('2d');
        var data = {
                labels: @Html.Raw(XLabels),
                datasets: [{
                    label: "Drinks Chart",
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderWidth: 1,
                    data: @Html.Raw(YValues)
    }]
            };

var options = {
                maintainAspectRatio: false,
                scales: {
                    yAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: true,
                            color: "rgba(255,99,164,0.2)"
                        }
}],
                    xAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: false
                        }
                    }]
                }
            };

       var myChart = new  Chart(ctx, {
                options: options,
                data: data,
                type:'pie'

            });
        });
</script>

Views/Charts/Stacked.cshtml
@model List<StackedViewModel>
@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject( Model.FirstOrDefault().LstData.Select( x => x.DimensionOne ).ToList() );
    var YValues = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.LstData.Select( w => w.Quantity ) ).ToList() );
    var label2 = Newtonsoft.Json.JsonConvert.SerializeObject( Model.Select( x => x.StackedDimensionOne ).ToList() );
    ViewData["Title"] = "Stacked Chart";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Stacked</title>
</head>
<body>
    <div class="box-body">

        <div class="chart-container">
            <canvas id="chartStacked" style="width:100%; height:500px"></canvas>
        </div>
    </div>
</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
        $(function () {
            var chartName = "chartStacked";
            var ctx = document.getElementById(chartName).getContext('2d');
            var XLabels = @Html.Raw(XLabels);
            var YValues = @Html.Raw( YValues );
            var label = @Html.Raw( label2 );
            var aux = 0;

            var barChartData = {
                labels:  @Html.Raw(label2),
                datasets: []
            }

            XLabels.forEach(function (a, i) {
                var data = [];
                YValues.forEach(function (a, i) {
                    data.push(a[aux]);
                });

            barChartData.datasets.push({
                label: XLabels[aux],
                backgroundColor: random_rgba(),
                data: data
                });
                aux++;
            });
            var options = {
                maintainAspectRatio: false,
                scales: {
                    yAxes: [{
                        ticks: {
                            min: 0,
                            beginAtZero: true
                        },
                        stacked: true,
                        gridLines: {
                            display: true,
                            color: "rgba(255,99,164,0.2)"
                        }
                    }],
                    xAxes: [{
                        stacked: true,
                        gridLines: {
                            display: false
                        }
                    }]
                }
            };
            function random_rgba() {
                var o = Math.round, r = Math.random, s = 255;
                return 'rgba(' + o(r() * s) + ',' + o(r() * s) + ',' + o(r() * s) + ',' + r().toFixed(1) + ')';
            }
            var myChart = new Chart(ctx, {
                options: options,
                data: barChartData,
                type: 'bar'

            });
        });
</script>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreCharts</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NetCoreCharts</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Charts" asp-action="Bar">Bar</a></li>
                    <li><a asp-area="" asp-controller="Charts" asp-action="Line">Line</a></li>
                    <li><a asp-area="" asp-controller="Charts" asp-action="Pie">Pie</a></li>
                    <li><a asp-area="" asp-controller="Charts" asp-action="Stacked">Stacked</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <br><br><br>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - NetCoreCharts</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>